openapi: 3.0.0
info:
  title: Agency Incoming API
  version: "1.0"
  description: API spec for agencies to process incoming requests from Freede.
servers: []
paths:
  /registration:
    post:
      summary: Register consumer
      tags:
        - Registration
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  description: ""
                  type: object
                  properties:
                    ref:
                      type: string
                      minLength: 1
                      description: Agency consumer reference number
                    desc:
                      type: string
                      minLength: 1
                      description: Account description
                    status_reason:
                      type: string
                      minLength: 1
                      description: Status reason to display to consumer
                    status:
                      type: string
                      enum:
                        - active
                        - paid_in_full
                        - paid_settlement
                        - disputed
                        - closed
                      description: Account status
                    balance_current:
                      type: number
                      description: Current total balance
                    balance_start:
                      type: number
                      description: Starting balance
                    balance_buckets:
                      type: array
                      uniqueItems: true
                      minItems: 1
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                            minLength: 1
                            description: Bucket name to display
                          balance_current:
                            type: number
                            description: Bucket current balance
                          balance_start:
                            type: number
                            description: Bucket starting balance
                          type:
                            type: string
                            minLength: 1
                            description: Bucket type
                            enum:
                              - principal
                              - interest
                              - fees
                              - other
                    agency:
                      type: object
                      properties:
                        ref:
                          type: string
                          minLength: 1
                          description: Agency account reference code
                        last_payment_amt:
                          type: number
                          description: Agency last payment amount
                        last_activity:
                          type: string
                          minLength: 1
                          format: date-time
                          description: Agency last activity
                        last_payment_date:
                          type: string
                          minLength: 1
                          format: date-time
                          description: Agency last payment date
                    creditor:
                      type: object
                      properties:
                        ref:
                          type: string
                          minLength: 1
                          description: Creditor account reference code
                        last_payment_amt:
                          type: number
                          description: Creditor last payment amount
                        last_activity:
                          type: string
                          minLength: 1
                          format: date-time
                          description: Creditor last payment activity
                        last_payment_date:
                          type: string
                          minLength: 1
                          format: date-time
                          description: Creditor last payment date
                        name:
                          type: string
                          minLength: 1
                          description: Creditor name
                    consumer:
                      type: object
                      properties:
                        ref:
                          type: string
                          description: Agency consumer reference
        "401":
          description: Unauthorized
      operationId: post-registration
      parameters:
        - schema:
            type: string
          in: header
          name: Freede-Verification-Key
          description: SHA256 Hash of Token and API key
        - schema:
            type: string
          in: header
          name: Freede-API-Version
          description: Freede Agency Incoming API Version
        - schema:
            type: string
          in: header
          name: Freede-Verification-Token
          description: Token Salt
      description: Freede will submit this POST request when a consumer is attempting
        to register with the agency. Agency may perform their own validation
        checks and return a response.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first:
                  type: string
                last:
                  type: string
                address:
                  type: string
                address2:
                  type: string
                city:
                  type: string
                state:
                  type: string
                zip:
                  type: string
                phone:
                  type: string
                email:
                  type: string
                  format: email
                regcode:
                  type: string
                verify:
                  type: boolean
                optins:
                  title: Optins
                  type: object
                  properties:
                    sms:
                      title: Optin
                      type: object
                      properties:
                        allowed:
                          type: boolean
                        default:
                          type: boolean
                    phone:
                      $ref: "#/paths/~1registration/post/requestBody/content/application~1json/schema\
                        /properties/optins/properties/sms"
                    email:
                      $ref: "#/paths/~1registration/post/requestBody/content/application~1json/schema\
                        /properties/optins/properties/sms"
                    push:
                      $ref: "#/paths/~1registration/post/requestBody/content/application~1json/schema\
                        /properties/optins/properties/sms"
              required:
                - regcode
                - verify
            examples: {}
        description: Consumer registration information
  "/account/{accountNum}":
    get:
      summary: Get account details
      tags:
        - Accounts
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/paths/~1registration/post/responses/200/content/application~1json/sche\
                  ma/items"
              examples: {}
        "204":
          description: No Content
      operationId: get-account
      parameters:
        - schema:
            type: string
          in: header
          name: Freede-Verification-Key
          description: SHA256 Hash of Token and API key
        - schema:
            type: string
          in: header
          name: Freede-API-Version
          description: Freede Agency Incoming API Version
        - schema:
            type: string
          in: header
          name: Freede-Verification-Token
          description: Token Salt
      description: Endpoint to get the account details from the agency
    parameters:
      - schema:
          type: string
        name: accountNum
        in: path
        required: true
        description: Agency account number
  /forms:
    post:
      summary: Consumer submitted form
      tags:
        - Forms
      responses:
        "200":
          description: OK
      operationId: post-forms
      parameters:
        - schema:
            type: string
          in: header
          name: Freede-Verification-Key
          description: SHA256 Hash of Token and API key
        - schema:
            type: string
          in: header
          name: Freede-API-Version
          description: Freede Agency Incoming API Version
        - schema:
            type: string
          in: header
          name: Freede-Verification-Token
          description: Token Salt
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  enum:
                    - dispute
                    - attorney
                    - bankruptcy
                form:
                  oneOf:
                    - description: ""
                      type: object
                      x-examples: {}
                      properties:
                        amount:
                          type: number
                          description: Amount in dispute.
                        reason:
                          type: string
                          minLength: 1
                          description: Dispute reason
                        bankruptcy:
                          description: ""
                          type: object
                          properties:
                            chapter:
                              type: string
                              minLength: 1
                            filing_date:
                              type: string
                              minLength: 1
                            discharge_date:
                              type: string
                              minLength: 1
                        attorney:
                          description: ""
                          type: object
                          properties:
                            name:
                              type: string
                              minLength: 1
                            lawfirm:
                              type: string
                              minLength: 1
                            phone:
                              type: string
                              minLength: 1
                            fax:
                              type: string
                              minLength: 1
                            email:
                              type: string
                              minLength: 1
                        accounts:
                          type: array
                          description: Agency reference numbers for accounts disputed.
                          items:
                            type: string
                      title: DisputeForm
                    - title: AttorneyForm
                      type: object
                      properties:
                        reason:
                          type: string
                        attorney:
                          $ref: "#/paths/~1forms/post/requestBody/content/application~1json/schema/proper\
                            ties/form/oneOf/0/properties/attorney"
                    - title: BankruptcyForm
                      type: object
                      properties:
                        bankruptcy:
                          $ref: "#/paths/~1forms/post/requestBody/content/application~1json/schema/proper\
                            ties/form/oneOf/0/properties/bankruptcy"
                        attorney:
                          $ref: "#/paths/~1forms/post/requestBody/content/application~1json/schema/proper\
                            ties/form/oneOf/0/properties/attorney"
      description: Endpoint to receive forms consumer has submitted
  "/consumer/{consumerRef}":
    parameters:
      - schema:
          type: string
        name: consumerRef
        in: path
        required: true
    put:
      summary: Update consumer demographics
      tags:
        - Consumers
      responses:
        "200":
          description: OK
      operationId: put-consumer-consumerRef
      parameters:
        - schema:
            type: string
          in: header
          name: Freede-Verification-Key
          description: SHA256 Hash of Token and API key
        - schema:
            type: string
          in: header
          name: Freede-API-Version
          description: Freede Agency Incoming API Version
        - schema:
            type: string
          in: header
          name: Freede-Verification-Token
          description: Token Salt
      requestBody:
        content:
          application/json:
            schema:
              description: ""
              type: object
              properties:
                first:
                  type: string
                  minLength: 1
                last:
                  type: string
                  minLength: 1
                address:
                  type: string
                  minLength: 1
                address2:
                  type: string
                  minLength: 1
                city:
                  type: string
                  minLength: 1
                state:
                  type: string
                  minLength: 1
                postal:
                  type: string
                  minLength: 1
                email:
                  type: string
                  minLength: 1
                phone:
                  type: string
                  minLength: 1
                ref:
                  type: string
                  minLength: 1
                  readOnly: true
      description: Endpoint to receive updated consumer demographics
    delete:
      summary: Deregister consumer
      operationId: delete-consumer-consumerRef
      parameters:
        - schema:
            type: string
          in: header
          name: Freede-Verification-Key
          description: SHA256 Hash of Token and API key
        - schema:
            type: string
          in: header
          name: Freede-API-Version
          description: Freede Agency Incoming API Version
        - schema:
            type: string
          in: header
          name: Freede-Verification-Token
          description: Token Salt
      responses:
        "200":
          description: OK
      description: Endpoint to deregister consumer from Freede
      tags:
        - Consumers
  "/consumer/{consumerRef}/optins":
    parameters:
      - schema:
          type: string
        name: consumerRef
        in: path
        required: true
        description: Agency consumer reference
    put:
      summary: Update consumer optins
      tags:
        - Consumers
      responses:
        "200":
          description: OK
      operationId: put-consumer-consumerRef-optins
      parameters:
        - schema:
            type: string
          in: header
          name: Freede-Verification-Key
          description: SHA256 Hash of Token and API key
        - schema:
            type: string
          in: header
          name: Freede-API-Version
          description: Freede Agency Incoming API Version
        - schema:
            type: string
          in: header
          name: Freede-Verification-Token
          description: Token Salt
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/paths/~1registration/post/requestBody/content/application~1json/schema\
                /properties/optins"
      description: Endpoint to receive updated consumer optins
  "/consumer/{consumerRef}/conversation":
    parameters:
      - schema:
          type: string
        name: consumerRef
        in: path
        required: true
    post:
      summary: Consumer conversation
      tags:
        - Consumers
      responses:
        "200":
          description: OK
      operationId: post-consumer-consumerRef-conversation
      parameters:
        - schema:
            type: string
          in: header
          name: Freede-Verification-Key
          description: SHA256 Hash of Token and API key
        - schema:
            type: string
          in: header
          name: Freede-API-Version
          description: Freede Agency Incoming API Version
        - schema:
            type: string
          in: header
          name: Freede-Verification-Token
          description: Token Salt
      requestBody:
        content:
          application/json:
            schema:
              title: Conversation
              type: object
              properties:
                type:
                  type: string
                  enum:
                    - chat
                    - phone
                    - email
                    - sms
                    - push
                  description: Type of conversation
                when:
                  type: string
                  format: date-time
                  description: When the conversation happened
                id:
                  type: string
                  description: Conversation Id
              description: Consumer conversation model
      description: Endpoint to receive notice of consumer conversation. Can use Id to
        retrieve conversation details from Agency API
tags:
  - name: Accounts
  - name: Consumers
  - name: Forms
  - name: Registration
