openapi: 3.0.0
info:
  title: Agency Incoming API
  version: '1.0'
  description: API spec for agencies to process incoming requests from Freede.
servers: []
paths:
  /registration:
    post:
      summary: Register consumer
      tags:
        - Registration
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/Account.v1.yaml
        '401':
          description: Unauthorized
      operationId: post-registration
      parameters:
        - schema:
            type: string
          in: header
          name: Freede-Verification-Key
          description: SHA256 Hash of Token and API key
        - schema:
            type: string
          in: header
          name: Freede-API-Version
          description: Freede Agency Incoming API Version
        - schema:
            type: string
          in: header
          name: Freede-Verification-Token
          description: Token Salt
      description: Freede will submit this POST request when a consumer is attempting to register with the agency. Agency may perform their own validation checks and return a response.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first:
                  type: string
                last:
                  type: string
                address:
                  type: string
                address2:
                  type: string
                city:
                  type: string
                state:
                  type: string
                zip:
                  type: string
                phone:
                  type: string
                email:
                  type: string
                  format: email
                regcode:
                  type: string
                verify:
                  type: boolean
                optins:
                  $ref: ../models/Optins.v1.yaml
              required:
                - regcode
                - verify
            examples: {}
        description: Consumer registration information
  '/account/{accountNum}':
    get:
      summary: Get account details
      tags:
        - Accounts
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/Account.v1.yaml
              examples: {}
        '204':
          description: No Content
      operationId: get-account
      parameters:
        - schema:
            type: string
          in: header
          name: Freede-Verification-Key
          description: SHA256 Hash of Token and API key
        - schema:
            type: string
          in: header
          name: Freede-API-Version
          description: Freede Agency Incoming API Version
        - schema:
            type: string
          in: header
          name: Freede-Verification-Token
          description: Token Salt
      description: Endpoint to get the account details from the agency
    parameters:
      - schema:
          type: string
        name: accountNum
        in: path
        required: true
        description: Agency account number
  /forms:
    post:
      summary: Consumer submitted form
      tags:
        - Forms
      responses:
        '200':
          description: OK
      operationId: post-forms
      parameters:
        - schema:
            type: string
          in: header
          name: Freede-Verification-Key
          description: SHA256 Hash of Token and API key
        - schema:
            type: string
          in: header
          name: Freede-API-Version
          description: Freede Agency Incoming API Version
        - schema:
            type: string
          in: header
          name: Freede-Verification-Token
          description: Token Salt
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  enum:
                    - dispute
                    - attorney
                    - bankruptcy
                form:
                  oneOf:
                    - $ref: ../models/Dispute-Form.v1.yaml
                    - $ref: ../models/AttorneyForm.v1.yaml
                    - $ref: ../models/BankruptcyForm.v1.yaml
      description: Endpoint to receive forms consumer has submitted
  '/consumer/{consumerRef}':
    parameters:
      - schema:
          type: string
        name: consumerRef
        in: path
        required: true
    put:
      summary: Update consumer demographics
      tags:
        - Consumers
      responses:
        '200':
          description: OK
      operationId: put-consumer-consumerRef
      parameters:
        - schema:
            type: string
          in: header
          name: Freede-Verification-Key
          description: SHA256 Hash of Token and API key
        - schema:
            type: string
          in: header
          name: Freede-API-Version
          description: Freede Agency Incoming API Version
        - schema:
            type: string
          in: header
          name: Freede-Verification-Token
          description: Token Salt
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Consumer.v1.yaml
      description: Endpoint to receive updated consumer demographics
    delete:
      summary: Deregister consumer
      operationId: delete-consumer-consumerRef
      parameters:
        - schema:
            type: string
          in: header
          name: Freede-Verification-Key
          description: SHA256 Hash of Token and API key
        - schema:
            type: string
          in: header
          name: Freede-API-Version
          description: Freede Agency Incoming API Version
        - schema:
            type: string
          in: header
          name: Freede-Verification-Token
          description: Token Salt
      responses:
        '200':
          description: OK
      description: Endpoint to deregister consumer from Freede
      tags:
        - Consumers
  '/consumer/{consumerRef}/optins':
    parameters:
      - schema:
          type: string
        name: consumerRef
        in: path
        required: true
        description: Agency consumer reference
    put:
      summary: Update consumer optins
      tags:
        - Consumers
      responses:
        '200':
          description: OK
      operationId: put-consumer-consumerRef-optins
      parameters:
        - schema:
            type: string
          in: header
          name: Freede-Verification-Key
          description: SHA256 Hash of Token and API key
        - schema:
            type: string
          in: header
          name: Freede-API-Version
          description: Freede Agency Incoming API Version
        - schema:
            type: string
          in: header
          name: Freede-Verification-Token
          description: Token Salt
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Optins.v1.yaml
            examples:
              Example:
                value:
                  sms:
                    allowed: true
                    default: false
                  phone:
                    allowed: true
                    default: false
                  email:
                    allowed: true
                    default: true
                  push:
                    allowed: true
                    default: false
      description: Endpoint to receive updated consumer optins
  '/consumer/{consumerRef}/conversation':
    parameters:
      - schema:
          type: string
        name: consumerRef
        in: path
        required: true
    post:
      summary: Consumer conversation
      tags:
        - Consumers
      responses:
        '200':
          description: OK
      operationId: post-consumer-consumerRef-conversation
      parameters:
        - schema:
            type: string
          in: header
          name: Freede-Verification-Key
          description: SHA256 Hash of Token and API key
        - schema:
            type: string
          in: header
          name: Freede-API-Version
          description: Freede Agency Incoming API Version
        - schema:
            type: string
          in: header
          name: Freede-Verification-Token
          description: Token Salt
      requestBody:
        content:
          application/json:
            schema:
              $ref: ../models/Conversation.v1.yaml
      description: Endpoint to receive notice of consumer conversation. Can use Id to retrieve conversation details from Agency API
tags:
  - name: Accounts
  - name: Consumers
  - name: Forms
  - name: Registration
